name: mongo pipeline

on:
  push:
    branches: [ "production" ]

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create ZIP deployment package
        run: cd backend && zip -r "deploy_package_${{ github.sha }}.zip" .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: "ap-southeast-2"

      - name: Upload package to S3 bucket
        run: cd backend && aws s3 cp "deploy_package_${{ github.sha }}.zip" s3://elasticbeanstalk-ap-southeast-2-650629407318/

      - name: Create new ElasticBeanstalk Application Version
        run: |
          aws elasticbeanstalk create-application-version \
          --application-name mongobackend \
          --source-bundle S3Bucket="elasticbeanstalk-ap-southeast-2-650629407318",S3Key="deploy_package_${{ github.sha }}.zip" \
          --version-label "ver-${{ github.sha }}" \
          --description "commit-sha-${{ github.sha }}"

      - name: Deploy new ElasticBeanstalk Application Version
        run: aws elasticbeanstalk update-environment --environment-name Mongobackend-env-1 --version-label "ver-${{ github.sha }}"

